### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Buyaki01** [Luckyaremu/html-form#2]
The code was readable
The page was responsive
Amazing work

**Comment by nyatindopatrick** [comment]
The code is clean though below are my suggestions:

- the node_modules folder should not be pushed to the remote repository
- The "**Create Account**" button should have "**type**" set to "**submit**" instead of "**name**"

**Comment by dili021** [comment]
very clean & readable. nothing to critique.

**Comment by Kyle-Law** [comment]
p-2-p review by @patriciachrysy classmate:
1)Regarding Header alignment: What you guys have done is that you've created 2 columns - 1fr for `<p>` and 100px for `<button>`, then text-align <p> to the right. Probably next time, try to align them horizontally using `justify-content: end;` rather than doing them separately.

**Comment by patriciachrysy** [comment]
Thank you guys for your reviews, I will surely apply them.
